# Generated by Django 4.2.9 on 2024-01-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
