# Generated by Django 4.2.9 on 2024-01-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=50)),
                ("organization_mailer_address", models.EmailField(max_length=254)),
                ("organization_mailer_password", models.CharField(max_length=100)),
                ("body", models.TextField()),
            ],
        ),
    ]
