# Generated by Django 4.2.9 on 2024-01-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_gallery_alter_announcement_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Giving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
