# Generated by Django 4.2.9 on 2024-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_meetingreport_welfare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welfare",
            name="member_name",
            field=models.CharField(max_length=100),
        ),
    ]
