# Generated by Django 4.2.9 on 2024-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="fontawesome_class",
            field=models.CharField(default="fa-user-graduate", max_length=50),
        ),
    ]
