# Generated by Django 4.2.9 on 2024-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_publication_fontawesome_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("breif_description", models.CharField(max_length=200)),
                ("event_date", models.DateTimeField()),
                ("registration_start_date", models.DateField(blank=True)),
                ("registration_end_date", models.DateField(blank=True)),
                ("registration_url", models.URLField()),
            ],
        ),
    ]
