# Generated by Django 4.2.9 on 2024-01-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="banner",
            field=models.ImageField(default="my_image.png", upload_to="events"),
            preserve_default=False,
        ),
    ]
