# Generated by Django 4.2.9 on 2024-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_event_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="file",
            field=models.FileField(
                default="demo_file.pdf", upload_to="publication_files"
            ),
            preserve_default=False,
        ),
    ]
