# Generated by Django 4.2.9 on 2024-02-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_publicationpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
