# Generated by Django 4.2.9 on 2024-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_publication_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationpayment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
