# Generated by Django 4.2.9 on 2024-02-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_publicationpayment_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="body",
        ),
    ]
