# Generated by Django 4.2.9 on 2024-06-05 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_announcement_action_text_announcement_action_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="uploadedAt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
