# Generated by Django 4.2.9 on 2024-09-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_event_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreport',
            old_name='details',
            new_name='general_comment',
        ),
    ]
