# Generated by Django 4.2.9 on 2024-09-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_details_meetingreport_general_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreport',
            name='city_nation',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingreport',
            name='moderator',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingreport',
            name='partners_name',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingreport',
            name='prayer_request',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
